#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    echo 'Warning: adminer-cli should be invoked via the CLI version of PHP, not the '.PHP_SAPI.' SAPI'.PHP_EOL;
}

$cliVersion = "0.6.0";
$adminerVersion = "4.3.1";

error_reporting(-1);

$options = getopt("hp:H:v:t:T");
$argv = $_SERVER['argv'];
if (isset($options['h'])) {
    echo <<<EOF
Usage: adminer [-p port] [-H host] [-v adminer_version] [-t theme]

Command line interface to run adminer on the PHP built-in server.
Copyright (c) Kohki Makimoto <kohki.makimoto@gmail.com>
Apache License 2.0

CLI version: $cliVersion
Adminer version: $adminerVersion

Options:
  -p    Listen port (default: 8080).
  -H    Listen host (default: 0.0.0.0).
  -t    Specify the theme (flat|nette|lucas-sandery|...).
        See https://github.com/kohkimakimoto/adminer-cli/tree/master/src/designs


EOF;
    exit(0);
}

$port = "8080";
if (isset($options['p'])) {
    $port = $options['p'];
}

$host = "0.0.0.0";
if (isset($options['H'])) {
    $host = $options['H'];
}

$theme = null;
if (isset($options['t'])) {
    $theme = $options['t'];
}

$rootDir = __DIR__;
$adminerPath = "$rootDir/src/adminer/adminer.php";
$routerScript = "$rootDir/src/router.php";

putenv("ADMINER_PATH=".$adminerPath);

if ($theme) {
    $themePath = "$rootDir/src/designs/$theme/adminer.css";
    if (!file_exists($themePath)) {
        echo "unsupported theme: $theme\n";
        exit(1);
    }
    putenv("ADMINER_THEME_PATH=".$themePath);
}

echo "Adminer runs on http://{$host}:{$port}\n";

passthru(PHP_BINARY." -d variables_order=EGPCS -S {$host}:{$port} {$routerScript}");
